##  第十二章 通过异常处理错误
Java的基本理念：结构不佳的代码不能运行。

发现错误的理想时机是在编译阶段，有些没有发现的只能在运行期间发现解决。
这样需要在运行时，错误源能通过某种方式将错误信息传递给处理问题的接收者。

错误恢复机制：提供代码健壮性最强有力的方式。错误恢复在每个程序中都是基本的要素。
Java使用异常来提供一致的错误报告模型，使得构件能够与客户端代码可靠地沟通问题。

异常处理是Java中唯一正式的错误报告机制，并且通过编译器强制执行。
Java中异常处理的目的：通过少于目前数量的代码来简化大型，可靠的程序的生成，并且让程序员相信应用中没有未处理的错误。

### 12.1 概念
C语言以及其他早期编程语言常常具有多种错误处理模式，但都不是属于语言的一部分，大部分是建立在约定俗成的基础。
例如通过约定返回值来判断是否发生了错误。这样需要在代码中加入很多错误检查，即使这些错误是来自被调用的代码。

Java：用强制规定的形式来消除错误处理过程中随心所欲的因素。通过异常可以降低错误处理代码的复杂度，将正常的逻辑代码和错误处理代码分开。

### 12.2 基本异常
**异常情形**是指阻止当前方法或作用域继续执行的问题。

**异常处理程序**:将程序从错误状态中恢复，以使程序能继续执行，或者换一种方式执行。

抛出异常：
```java
if(t == null) {
	throw new NullPointerException();
}
```

异常允许我们强制停止程序的运行，并且提示出现了什么问题，或者强制处理问题，并返回到稳定状态。

###  12.2.1 异常参数
标准异常类有两个构造器：
 - 默认构造器
 - 接收字符串作为参数

```java
if(t == null) {
	throw new NullPointerException();
}

if(t == null) {
	throw new NullPointerException("t == null");
}

```

一般返回的异常类型与方法正常的返回类型是不一样的，通过 关键字**throw**可以将生成的异常对象返回，效果跟从方法返回的一样。

Throwable：能够抛出任意类型的异常，是异常类型的根类。通常异常对象中仅有的信息就是异常类型，除此之外不包含其他任何有意义的内容。

### 12.3 捕获异常
**监控区域**:一段可能产生异常的代码，并且后面跟着处理这些异常的代码。

#### 12.3.1 try 块
用**try**块来捕获异常： 是跟在**try**关键字后面的普通程序块
```java
try {
	// 可能产生异常的代码
}
```

#### 12.3.2 异常处理程序

异常处理程序：针对每个捕获的异常，需要准备相应的处理程序。
异常处理紧跟在**try**块后面的，关键字是**catch**
```java
try {
	//可能产生异常的代码
} catch ( Type1 id1) {
	//异常类型type1 的处理方法
} catch( Type2 id2) {
	//异常类型Type2的处理方法
}
//etc....
```

每个catch字句（异常处理程序）看起来就像是接收一个且仅接受一个特殊类型的参数的方法。
当异常被抛出时，异常处理机制将负责搜寻参数与异常类型相匹配的第一个处理程序，然后进入catch字句执行。一旦catch字句结束，这处理结束。（switch语句需要在每个case跟一个break，不然会继续往下执行）

异常处理两个基本模型：
 1. 终止模型：关键错误，无法返回异常发生点继续执行，一旦异常被抛出，表明错误无法挽回，无法回来继续执行。
 2. 恢复模型：修正错误，重新尝试调用出问题的方法，通常希望异常被处理后能够继续执行程序。（Java实现类似恢复行为，需要不抛出异常，而是调用方法来修正，或者在while循环里一直执行try，直到满意的结果）

为了降低代码编写和维护的困难，一般都是选择终止模型，而不是恢复模型。因为恢复模型需要了解异常地点，需要写更多非通用的代码。

### 12.4 创建自定义异常
Java已经有很多异常类型，但不是所有异常都有，所有可以自己定义异常类来表示程序中可能会遇到的特定问题。
自己定义的异常类，必须从已有的异常类继承。

```java
class SimpleException extends Exception {}

public class InheritingExceptions {
  public void f() throws SimpleException {
    System.out.println("Throw SimpleException from f()");
    throw new SimpleException();
  }
  public static void main(String[] args) {
    InheritingExceptions sed = new InheritingExceptions();
    try {
      sed.f();
    } catch(SimpleException e) {
      System.out.println("Caught it!");
    }
  }
} /* Output:
Throw SimpleException from f()
Caught it!
*///:~
```
编译器创建了默认构造器，会自动调用基类的默认构造器。没有带String参数的构造器，默认的已经够用了。
```java
//也可以为异常类定义一个接受字符串参数的构造器
class MyException extends Exception {
  public MyException() {}
  public MyException(String msg) { super(msg); }
}

public class FullConstructors {
  public static void f() throws MyException {
    System.out.println("Throwing MyException from f()");
    throw new MyException();
  }
  public static void g() throws MyException {
    System.out.println("Throwing MyException from g()");
    throw new MyException("Originated in g()");
  }
  public static void main(String[] args) {
    try {
      f();
    } catch(MyException e) {
      e.printStackTrace(System.out);
    }
    try {
      g();
    } catch(MyException e) {
      e.printStackTrace(System.err);  //输出到标准错误流会比较好，因为System.out可能会被重定向。e.printStackTrace() 默认是输出到标准错误流。
    }
  }
} /* Output:
Throwing MyException from f()
MyException
        at FullConstructors.f(FullConstructors.java:11)
        at FullConstructors.main(FullConstructors.java:19)
Throwing MyException from g()
MyException: Originated in g()
        at FullConstructors.g(FullConstructors.java:15)
        at FullConstructors.main(FullConstructors.java:24)
*///:~
```

Throwable类中声明的printStackTrace()方法，打印从方法调用处直到异常抛出处的方法**调用序列**。

### # 12.4.1 异常与记录日志
通过改写自定义的异常类，将异常输出到日志中，一般使用java.util.logging工具。
还可以修改异常类的方法来增强功能，但一般开发人员只是查看异常类型，所以根本用不上其他功能。

### 12.5 异常说明
Java鼓励人们把方法可能会抛出的异常告知使用此方法的客户端程序员。这样调用者能确切的知道怎么捕获所有潜在的异常。
Java使用了**异常说明**来实现告知某个方法可能会抛出的的异常类型。使用关键字**throws**，它是属于方法声明的一部分，紧跟在形式参数列表后面：
```java
void f() throws TooBig, TooSmall, DivZero {
	//to-do
}
```
### 12.6 捕获所有异常
可以通过捕获一个异常类型的基类**Exception**来实现：一个异常处理程序捕获所有类型的异常。
```java
catch(Exception e) {
	//TO-DO
}
```
最好将这个放在处理程序的末尾，以防它抢在其他处理程序之前先把异常捕获了。

### 12.6.1 栈轨迹
printStackTrace() 方法：打印栈轨迹元素所构成的数组，每一个元素都表示栈中的一帧。
元素0是栈顶元素，表示调用序列中的最后一个方法调用，也是Throwable被创建和抛出的地方；
数组最后一个元素时调用序列中第一个方法调用。

```java
public class WhoCalled {
  static void f() {
    // Generate an exception to fill in the stack trace
    try {
      throw new Exception();
    } catch (Exception e) {
      for(StackTraceElement ste : e.getStackTrace())
        System.out.println(ste.getMethodName());
    }
  }
  static void g() { f(); }
  static void h() { g(); }
  public static void main(String[] args) {
    f();
    System.out.println("--------------------------------");
    g();
    System.out.println("--------------------------------");
    h();
  }
} /* Output:
f
main
--------------------------------
f
g
main
--------------------------------
f
g
h
main
*///:~
```


#### 12.6.2 重新抛出异常
把刚捕获的异常重新抛出：
```
catch(Exception e) {
	System.out.println("An Exception was whrown");
    throw e;  //这样外层捕获的异常的发生地点还是上面的try
    //!throw (Exception)e.fillInStackTrace();  //这样外面捕获的异常的发生地就是这一行代码
}
```
可以在捕获A异常后，重新抛出B类型异常。原来A类型相关的信息就会丢失，剩下的就是与新的异常发生地点相关的B异常的信息。

#### 12.6.3 异常链
常常会在捕获A类型异常后抛出B类型异常，并且希望把A类型的异常信息保存下来，这样被称为**异常链**。
可以使用**cause**对象作为Throwable构造器的参数，从而将原始异常传递给新的异常。

Throwable的子类中，只有Error、Exception和RuntimeException三种基本异常类提供了待cause参数构造器，其他的类只能使用initCause()方法而不是构造器。

### 12.7 Java标准异常

Throwable这个Java类被用来表示可以作为异常被抛出的类。
Throwable对象的导出类可以分为两种类型：
 1. Error：编译时和系统错误，一般不用关心
 2. Exception：是可以被抛出的基本类型。在Java类库、用户方法以及运行时故障都可能抛出Exception型异常。
 
 所以程序员关心的通常都是Exception类。
 
学习异常，关键是理解概以及如何使用：
 - 概念： 通过异常名称来表示发生的问题，望文知意。
 - 使用：


#### 12.7.1 特例： RuntimeException
如果对null引用进行调用，Java会自动抛出NullPointerException，这个是java标准运行时检测的一部分。
运行时异常会被Java虚拟机自动抛出，且都是从RuntimeException继承来的，不必在异常说明中列出来。
RuntimeException也成为**不受检查异常**
虽然不用显示的用try来捕获RuntimeException，但还是可以直接抛出RuntimeException类型异常的。
这样就可能会导致RuntimeException类型的异常穿越所有的执行路径直达main()方法，而不会被捕获。
```java
public class NeverCaught {
  static void f() {
    throw new RuntimeException("From f()");
  }
  static void g() {
    f();
  }
  public static void main(String[] args) {
    g();  //异常被抛出后，没有被捕获
  }
} ///:~
```

### 12.8 使用finally进行清理
无论try块中的异常是否抛出，都希望能够得到执行的代码可以放在**finally**中。一般是用来处理回收内存回收之外的情况。（内存回收时由垃圾回收器完成）
完整代码：
```java
public class FinallyWorks {
  static int count = 0;
  public static void main(String[] args) {
    while(true) {
      try {
        // Post-increment is zero first time:
        if(count++ == 0)
          throw new ThreeException();
        System.out.println("No exception");
      } catch(ThreeException e) {
        System.out.println("ThreeException");
      } finally {
        System.out.println("In finally clause");
        if(count == 3) break; // out of "while" //无论是否捕获到异常，都会执行。直到count==3才会break跳出while循环
      }
    }
  }
} /* Output:
ThreeException
In finally clause  //第一次抛出异常后执行finally
No exception    
In finally clause   //第二次没有抛出异常后执行finally
No exception
In finally clause   //第三次没有抛出异常后执行finally。break跳出while循环
*///:~
```

#### 12.8.1 finally用来做什么
对于没有垃圾回收和析构函数自动调用机制的编程语言来说，finally很重要。

但是Java有垃圾回收机制，所以不需要finally来处理内存回收的问题。

Java中finally使用场景：
 - 除内存之外的资源恢复到初始状态时，需要用到finally字句。例如需要清理的资源：打开的文件或网络连接，屏幕上的图形

不管是没有抛出异常，还是抛出异常被捕获，甚至是抛出的异常没有被异常处理程序捕获的情况下，异常处理机制也会在跳到更上一层的异常处理程序之前，执行finally语句。

#### 12.8.2 在return中使用finally
因为**finally**语句总会执行，所以在一个方法中，可以从多个点返回，并且可以保证重要的清理工作仍旧会执行：
```java
public class MultipleReturns {
  public static void f(int i) {
    System.out.println("Initialization that requires cleanup");
    try {
      System.out.println("Point 1");
      if(i == 1) return;
      System.out.println("Point 2");
      if(i == 2) return;
      System.out.println("Point 3");
      if(i == 3) return;
      System.out.println("End");
      return;
    } finally {
      System.out.println("Performing cleanup\n");
    }
  }
  public static void main(String[] args) {
    for(int i = 1; i <= 4; i++)
      f(i);
  }
} /* Output:
Initialization that requires cleanup
Point 1
Performing cleanup

Initialization that requires cleanup
Point 1
Point 2
Performing cleanup

Initialization that requires cleanup
Point 1
Point 2
Point 3
Performing cleanup

Initialization that requires cleanup
Point 1
Point 2
Point 3
End
Performing cleanup
*///:~
```
可以看出在finally内部，从何处放回无关紧要。

### 12.8.3 缺憾：异常丢失
finally中的如果使用了某些特殊语句，会导致异常缺失：
 1. try 抛出异常A，finally抛出异常B，这样外层catch时就会丢失A
 2. try抛出异常A，finally直接return，这样即使抛出了异常，也不会 有任何输出。



### 12.9 异常的限制
当覆盖方法的时候，只能抛出在基类方法的异常说明里列出的那些异常。
异常限制对构造器不起作用。导出类构造器的异常说明必须包含基类构造器的异常说明。
导出类构造器不能捕获基类构造器抛出的异常。


### 12.10 构造器
编码过程中，需要时刻询问自己：如果异常发生了，所有的东西能够被正确清理吗？

正常的清理是放在finally语句中实现的，如果构造器在执行过程中故障，那么对象没有被创建成功，这时finally也是不能被执行的，finally字句反而是要被清理的对象。

对于在构造阶段可能会抛出异常，并且要求清理的类，最安全的使用方式是使用嵌套的try语句：
```java
public class InputFile {
  private BufferedReader in;
  public InputFile(String fname) throws Exception {
    try {
      in = new BufferedReader(new FileReader(fname));
      // Other code that might throw exceptions
    } catch(FileNotFoundException e) {
      System.out.println("Could not open " + fname);
      // Wasn't open, so don't close it
      throw e;
    } catch(Exception e) {
      // All other exceptions must close it
      try {
        in.close();
      } catch(IOException e2) {
        System.out.println("in.close() unsuccessful");
      }
      throw e; // Rethrow
    } finally {
      // Don't close it here!!!
    }
  }
  public String getLine() {
    String s;
    try {
      s = in.readLine();
    } catch(IOException e) {
      throw new RuntimeException("readLine() failed");
    }
    return s;
  }
  public void dispose() {
    try {
      in.close();
      System.out.println("dispose() successful");
    } catch(IOException e2) {
      throw new RuntimeException("in.close() failed");
    }
  }
} ///:~
```

```java
public class Cleanup {
  public static void main(String[] args) {
    try {
      InputFile in = new InputFile("Cleanup.java");
      try {
        String s;
        int i = 1;
        while((s = in.getLine()) != null)
          ; // Perform line-by-line processing here...
      } catch(Exception e) {
        System.out.println("Caught Exception in main");
        e.printStackTrace(System.out);
      } finally {
        //在InputFile创建时，构造成功了就会进入finally，创建失败就不会进入finally。
        in.dispose();
      }
    } catch(Exception e) {  //如果上面创建InputFile构造过程中失败，那么就会在这里捕获，不会执行上面的finally的dispose()语句。（因为打开文件失败，所以不需要关闭文件）
      System.out.println("InputFile construction failed");
    }
  }
} /* Output:
dispose() successful
*///:~
```
基本规则：在创建需要清理的对象时候，立即进入一个try-finally语句块。

```java
class NeedsCleanup { // Construction can't fail
  private static long counter = 1;
  private final long id = counter++;
  public void dispose() {
    System.out.println("NeedsCleanup " + id + " disposed");
  }
}

class ConstructionException extends Exception {}

class NeedsCleanup2 extends NeedsCleanup {
  // Construction can fail:允许构造器失败，需要抛出异常
  public NeedsCleanup2() throws ConstructionException {}
}

public class CleanupIdiom {
  public static void main(String[] args) {
    // Section 1:
    NeedsCleanup nc1 = new NeedsCleanup();
    try {
      // ...
      //这里没有catch，表明不能创建失败，如果失败，直接清理，然后终止。
    } finally {
      nc1.dispose();
    }

    // Section 2:
    // If construction cannot fail you can group objects:
    NeedsCleanup nc2 = new NeedsCleanup();
    NeedsCleanup nc3 = new NeedsCleanup();
    try {
      // ...
    } finally {
      nc3.dispose(); // Reverse order of construction,需要跟前面创建的顺序相反。
      nc2.dispose();
    }

    // Section 3:
    // If construction can fail you must guard each one:
    //如果允许失败的构造器，且需要清理。这是需要每个构造器必须包含在自己的try-finally语句块中：
    try {
      NeedsCleanup2 nc4 = new NeedsCleanup2();
      try {
        NeedsCleanup2 nc5 = new NeedsCleanup2();
        try {
          // ...
        } finally {
          nc5.dispose();  //清理nc5，创建nc5才会进入这里
        }
      } catch(ConstructionException e) { // nc5 constructor
        System.out.println(e);
      } finally {
        nc4.dispose(); //清理nc4，创建nc4才会进入这里
      }
    } catch(ConstructionException e) { // nc4 constructor
      System.out.println(e);
    }
  }
} /* Output:
NeedsCleanup 1 disposed
NeedsCleanup 3 disposed
NeedsCleanup 2 disposed
NeedsCleanup 5 disposed
NeedsCleanup 4 disposed
*///:~
```


### 12.11 异常匹配
抛出异常的时候，异常处理系统会按照代码的书写顺序找出最近的处理程序。匹配后就认为得到处理，不再往下继续查找。

查找的时候不需要完全匹配，导出类的对象也可以匹配器基类的处理程序。catch(E a) 会捕获E类及其导出类的异常。
如果把捕获基类的catch字句放在前面，就会把后面导出类的异常全都屏蔽掉。


### 12.12 其他可选方式
在发生异常状况，正常的执行已经不可能或不需要了，这时异常处理系统就会帮助处理这种异常情况。
开发异常处理的初衷就是为了方便程序员处理错误；
异常处理的一个重要原则就是：只有在你知道如何处理的情况下才能捕获异常；
异常处理的一个重要目标就是：把错误处理的代码和错误发生地点分离，这样可以在正常代码中更加专注于要完成的是事情。

当项目比较小时，异常说明能增加开发人员的效率，提高代码质量。
但是项目越来越大时，会导致开发效率变低，而代码质量只有微不足道的提高。
因为**被检查异常**强制加上catch语句，即使还没有准备好处理错误的时候，就要求必须加上catch处理语句了。

解决方法：
#####   把异常传递给控制台 
```Java
public class MainException {
  // Pass all exceptions to the console:
  //使用了throws  Exception，这样在main()方法里面就不用写try-catch语句了
  public static void main(String[] args) throws Exception {
    // Open the file:
    FileInputStream file =  new FileInputStream("MainException.java");
    // Use the file ...
    // Close the file:
    file.close();
  }
} ///:~
```
##### 把"被检查的异常"转换为"不检查的异常"
RuntimeException就是不检查的异常。可以用RuntimeException来"包装"被检查异常：

### 12.13 异常使用指南
应该在下列情况下使用异常：
1. 在恰当的即被处理问题，知道在改如果处理的情况下才捕获异常。
2. 解决问题并且重新调用产生异常的方法；
3. 进行少许修补，然后绕过异常发生的地方继续执行；
4. 用别的数据进行计算，以代替方法预计会返回的值；
5. 把当前运行环境能做的事情尽量做完，然后把相同的异常重新抛到更高层；
6.把当前运行环境下能做的事情进来做完，探后吧不同的异常重新抛到更高层；
7.终止程序；
8.进行简化，如果所使用的异常模式使问题变复杂，那么使用起来会变得很痛苦也很烦人
9.让类库和程序更加安全，提高程序健壮性。


### 12.14 总结
异常是Java中不可分割的一部分。许多类库都需要使用异常处理。
异常处理的优点：
 1. 可以集中精力处理需要解决的问题，而在另一块地方处理这段代码产生的错误。
 2. 异常主要的目的是报告异常的产生，而恢复的功能实现占少数，不到10%.





















